### ISSUE TITLE
Formatting: length and special sections

### ISSUE THREAD

**Issue by JPFrancoia** [josephwright/achemso#19]
Hi,

I don't know if this repo is still active, or if it is providing "official" support (is the ACS involved ?).

However, I have a few comments about this package. First, it's great. Second, I think it suffers minor issues, avoiding its use by most.

Me and and a friend tested both the Word template and the LaTex template to write the exact same publication, in the form of a JACS communication. We noted a few points:
- The hyphenation with the LaTex template makes the text almost unreadable. With a two columns format, words are cut every two lines. A work around is to use: \hyphenpenalty=750
- The font is smaller with the LaTex package. We printed the publication written with the two templates, and the difference is obvious
- Special sections, like Author Information (where you can note you have "No competing financial interests") are impossible to create

Finally, we observed the publication written with the Latex template is drastically shorter. Maybe 30 to 40 %. I know the user manual mentions some of these points, especially the length. But it's very brief, and the final user doesn't know which changes the editors will apply on the paper. Basically, if the user writes the publication only with LaTex, he doesn't know the REAL length of his article. But he can still trust the journal to make the final changes. The real problem lies here: while the final form of the paper will be perfectly formatted, a pdf has to be sent to the reviewers. And a 2 pages communication is not very credible, neither is a text completely hyphenated.

The lack of documentation on this point + the visible difference between the two templates + the difficulty to be accepted in a ACS journal can kill the use of this package.

Can we do something about that ?

**Comment by josephwright** [comment]
Whilst the ACS has a central publication office, each journal is edited independently. Thus although I have (reasonably) regular contact from the ACS, the requirements from individual journals come through only sporadically. In terms of _JACS_, I've had very little information/contact over the time I've maintained `achemso`, and certainly nothing direct concerning 'print like' layouts.

I have asked the ACS in the past about the desirability (or otherwise) of setting up a 'print like' layout for communications, but this was not at the time encouraged. I will discuss this again with my ACS contacts: the situation may have changed.

**Comment by rififi** [comment]
Ok, thank you for your concern.

Do you know if it's possible to contact directly an editor (maybe a guy at the very end of the 'printing' process), and ask him directly ?

Anyway, could you keep us posted ?

In the future, I'll be very glad to test changes made to the achemso package.

**Comment by josephwright** [comment]
I've mailed my contact at the ACS: he knows people in both the editorial offices and in production. It's important to note that production is essentially a separate process from the editorial side: what the editorial offices want for review doesn't really impact on what production need for typesetting.

**Comment by JPFrancoia** [comment]
Hi, any news regarding this issue ? I'm still interested.

**Comment by josephwright** [comment]
I have been specifically asked _not_ to match print layout: the ACS are _very_ clear on this.
