### ISSUE TITLE
Change history lists versions in incorrect order

### ISSUE THREAD

**Issue by anntzer** [josephwright/achemso#21]
Very minor issue: in the pdf doc of v3.10g (2016/10/04), the versions in the change history are listed in the order
> v1.0 v2.0 v3.0 v3.1 v3.10 v3.10a ... v3.2 etc.

instead of "numerical" order.

**Comment by josephwright** [comment]
This is a feature of the indexing used to create change lists by `ltxdoc`, not part of `achemso`.
