### ISSUE TITLE
Error in compilation for the demo

### ISSUE THREAD

**Issue by jlorieau** [josephwright/achemso#24]
I have texlive2017 (MacTex) installed on my system. When I try to compile the achemso demo, ```achemso-demo.tex```, I get the following error:

```
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! LaTeX error: "kernel/command-not-defined"
! 
! Control sequence \regex_match:NnTF undefined.
! 
! See the LaTeX3 documentation for further information.
! 
! For immediate help type H <return>.
!...............................................
```

I looked through the loaded packages, and it appears to be a problem in the mhchem.sty. This package was updated recently:

```
\ProvidesPackage{mhchem}[2017/07/24 v4.07 for typesetting chemical formulae]
```

Indeed, when I remove the mhchem package from the demo (and the corresponding ```\ce``` tags), the document compiles as expected.

I believe this is an error that should be fixed in mhchem. However, I wonder whether there is a solution that could be added to the preamble of the ```achemso-demo.tex``` file. I would expect this file to compile without modification.

As a related suggestion, I'd recommend incorporating Travis-CI and a ```.travis.yml``` in the package. I haven't used this for a latex package, but it would be helpful for testing the build of ```achemso-demo.tex``` for dependent package updates.

**Comment by josephwright** [comment]
The demo now uses `chemformula` ...
