### ISSUE TITLE
crtoec journal formatting issues

### ISSUE THREAD

**Issue by shrx** [josephwright/achemso#25]
When I compile a latex article using the achemso document class and crtoec journal formatting, there are some issues and inconsistencies with the guidelines.

1) There appears a "Running header" section below the author's information on the first page.
2) The article's title is repeated under the "Running header" section.
3) The TOC graphic is incorrectly placed at the end of the article instead of above the abstract.

**Comment by josephwright** [comment]
The ACS are moving to a common review format. Even without this, these things are really only minor wrinkles: the typesetters change everything anyway ...
