### ISSUE TITLE
Class option "journal" does not work for ACS Energy Letters

### ISSUE THREAD

**Issue by JulianeB42** [josephwright/achemso#26]
According to the documentation the setting that should be used for ACS Energy Letters is "aelccp". When I use it (for example like this: \documentclass[journal = aelccp, manuscript=letter]{achemso}) I get an error message saying: "Unknown journal `aelccp': (achemso) using default configuration JACSAT" Would be great if this could be resolved.

**Comment by josephwright** [comment]
Which version of `achemso` do you have?

**Comment by JulianeB42** [comment]
Thanks for getting back to me. I was originally using the template that is hosted on overleaf, but today downloaded the achemso ZIP from CTAN and could reproduce the same problem when changing the journal in the demo file that comes with that. So that should be version 3.10i 2017-05-18
