### ISSUE TITLE
Require a synopsis for achemso template

### ISSUE THREAD

**Issue by lt6152** [josephwright/achemso#39]
When I used achemso template to submit a manuscript on environmental science and technology journal, they required a synopsis after keywords. But I do not know how to add this. Could you please teach me how to do that? I am a rookie in Latex but I like to use it. Thanks for your help.
![微信图片_20220818105336](https://user-images.githubusercontent.com/88485400/185282666-6ddf6999-b673-4f48-b800-c01eacd980f3.png)

**Comment by josephwright** [comment]
I'm not sure if you mean here you were able to sort it?
