### ISSUE TITLE
"Unused global options" for class options

### ISSUE THREAD

**Issue by Jellby** [josephwright/achemso#42]
It seems passing options to `\documentclass` triggers a "Unused global option(s)" warning, even if the options are obviously used:

```
\documentclass[journal=jctcce,manuscript=suppinfo]{achemso}
\title{Foo}
\begin{document}
Bar
\end{document}
```
```
LaTeX Warning: Unused global option(s):
    [journal=jctcce,manuscript=suppinfo].
```

**Comment by jfdoolster** [comment]
same thing here:
```latex
\documentclass[email=false]{achemso}
\title{foo}
\begin{document}
bar
\end{document}
```

```
Unused global option(s):
    [email=false].
```

**Comment by josephwright** [comment]
I'm wondering if I want to risk a fix here: would mean a change of option handler, and that's likely to cause wider issues

**Comment by jfdoolster** [comment]
> I'm wondering if I want to risk a fix here: would mean a change of option handler, and that's likely to cause wider issues

not worth causing other issues, warning can be ignored similar to over/underfill

**Comment by fxcoudert** [comment]
I would argue this is actually a pain point: some TeX software knows that overfill/underfill are a different category and has options to silence them (or put them in a separate category). But class warnings are generally serious, and show up. This is the case in Overleaf for example, and having warnings that show up in all cases mean that users simply start ignoring all warnings, which is bad habit.

**Comment by josephwright** [comment]
I gave this a bit more thought. It's not actually an `achemso` issue _per se_ as it's arisen due to changes in option handling more generally. Now, true, I could simply use a different option handling approach, but I will take a look at the underlying issue first.

**Comment by josephwright** [comment]
Right, we seem to have an idea where this comes from: definitely an `xkeyval` issue. I'm wondering about whether to move away to `ltkeys`, but that has some tricky aspects too.

**Comment by josephwright** [comment]
I've taken another look at a fix from the `achemso` end and it's simply too risky at the moment. We need the code to work with LaTeX from at least five if not 10 years ago, so any 'conditional' setup becomes horrible.

**Comment by josephwright** [comment]
Right, I decided that at this stage `xkeyal` can't be dropped, but I can force-suppress the warning, which I hope is acceptable.
