### ISSUE TITLE
Add the "Data Availability Statement" section

### ISSUE THREAD

**Issue by zxdawn** [josephwright/achemso#43]
According to the [ACS website](https://publish.acs.org/publish/data_policy), they prefer adding the `Data Availability Statement` section.

**Comment by josephwright** [comment]
Sure, but with hindsight I'd probably not even provide a 'pre-built' text for supplementary info. Thi sis best handled jus tby the author having
```latex
\section*{Data availability statement}
<Appropriate text>
```
in their source.

**Comment by zxdawn** [comment]
Ha, got it. I will add the section directly. Thanks!
