### ISSUE TITLE
Bibliography: include all authors instead of 'et.al.'

### ISSUE THREAD

**Issue by alfredoq** [josephwright/achemso#46]
Hello, 

I am submitting to the Journal of Chemical Information and Modeling journal, and was asked to include all authors explicitly in the bibliography. However the template chops the authors name and indicates 'et.al'.

Is there a way to indicate the template to include all authors? 

Thanks in advance,

Alfredo

**Comment by josephwright** [comment]
Use 
```latex
\setkeys{acs}{maxauthors = 0}
```
then re-run LaTeX/BibTeX/LaTeX/LaTeX.

**Comment by alfredoq** [comment]
I used the keyword as follows:

\documentclass[journal=jcisd8,manuscript=article]{achemso}
\setkeys{acs}{maxauthors = 0}
...

however 'et al.' is still being added, am I doing something wrong?

**Comment by josephwright** [comment]
I'd need to see a full example - it should be fine. Can you mail an example to me (joseph@texdev.net).

**Comment by alfredoq** [comment]
I was able to track down the error while preparing the example: the 'and others' was hard coded within the reference in question, since the bibtex database didnt contained the full list of authors. 

I added them manually and worked as expected.

Thank you very much for the support.

Closing the issue.
