### ISSUE TITLE
Setting etalmode=truncate and maxauthors=0 in the class options still truncates to et~al

### ISSUE THREAD

**Issue by josephwright** [josephwright/achemso#7]
I have a manuscript for JCTC, and I have put the following on top of my LaTeX file (`manuscript.tex`):

```
\documentclass[english,journal=jctcce,etalmode=truncate,maxauthors=0]{achemso}
```

I expected this to not truncate any author lists in the references, but unfortunately the behaviour is the same as without the options: lists longer than 15 names are truncated.

Oddly, when running latex, a file `acs-manuscript.bib` is created: **

```
This is an auxiliary file used by the `achemso' bundle.
This file may safely be deleted. It will be recreated as required.

@Control{achemso-control,
ctrl-use-title     =  "no",
ctrl-etal-number   =  "15",
ctrl-etal-firstonly =  "yes",
}
```

So it seems that the options do not get set correctly in this temporary file. If I change the values in `acs-manuscript.bib`, e.g. setting `ctrl-etal-number = "0"`, and `ctrl-etal-firstonly = "no"`, then the correct full author list is generated when running BibTeX.

**Comment by salotz** [comment]
I know this is really old. But I am having this issue. This code:

```
\documentclass[journal = acsodf, manuscript = article, layout = traditional]{achemso}
\usepackage[articletitle=true, etalmode = truncate, maxauthors = 10]{achemso}
```

Is giving me the `acs-{my-file}.bib` as:

```
This is an auxiliary file used by the `achemso' bundle.
This file may safely be deleted. It will be recreated as required.
 
@Control{achemso-control,
  ctrl-article-title  = "yes",
  ctrl-chapter-title  = "no",
  ctrl-doi            = "no",
  ctrl-etal-number    = "15",
  ctrl-etal-firstonly = "yes",
}

```

No matter what. If I use the setkeys like this:

```
\documentclass[journal = acsodf, manuscript = article, layout = traditional]{achemso}

\usepackage[]{achemso}
\setkeys{acs}{articletitle = true}
\setkeys{acs}{etalmode = truncate}
\setkeys{acs}{maxauthors = 10}
```

I get the correct `acs-{file}.bib`:

```
\documentclass[journal = acsodf, manuscript = article, layout = traditional]{achemso}

\usepackage[]{achemso}
\setkeys{acs}{articletitle = true}
\setkeys{acs}{etalmode = truncate}
\setkeys{acs}{maxauthors = 10}
```

**Comment by josephwright** [comment]
If you load the class and the package, all bets are off!
